import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

// ============================================================================
// TODO — READ BEFORE TOUCHING THIS FILE
// ============================================================================
// This file was reconstructed from a PDF export of the original Base44
// source (PDFs don't preserve non-Latin/RTL text reliably — lines get
// reordered, split mid-word, or scrambled during extraction).
//
// Only English below rebuilt cleanly. Hindi's KEYS match the app's key
// structure, but its CONTENT carries systematic extraction damage (a space
// inserted after most consonant+ि clusters, e.g. "वि त्तीय" for "वित्तीय") —
// do not trust it; restore it from the real source along with the rest.
// Urdu, Arabic, Tamil, Telugu, Punjabi, and Bengali were too corrupted to
// safely reconstruct (content was tangled across unrelated keys in places)
// and have been replaced with empty stubs below so the app builds and
// runs — those 6 languages currently fall back to English via the `t()`
// function's fallback chain (see bottom of this file). NOTE also the
// key-normalization bug described in TODO-11: the Urdu/Arabic keys here
// differ byte-wise from the ones used by the Header/PreferencesInfo
// selectors and the rtlLanguages array below, so selecting them falls back
// to English text but still flips the layout to RTL.
//
// ACTION NEEDED: replace this entire file with the real version from the
// Base44-synced GitHub repo before launch. Do not hand-translate a
// replacement — it must match the app's exact key structure.
// ============================================================================

const translations = {
English: {
// Header & Navigation
selectLanguage: "Select Language",
createProfile: "Create Profile",
aiAgent: "AI Agent",
financialServicesNav: "Financial Services",
partnersNav: "Partners",
// Hero Section
aiPowered: "AI-Powered Financial Inclusion",
heroTitle: "Empowering the Unbanked",
heroSubtitle: "Connect with microfinance institutions, small banks, and government programs through our multilingual AI assistant. Making financial services accessible to 1.4 billion adults worldwide.",
getStarted: "Get Started Today",
watchDemo: "Watch Demo",
voiceEnabled: "Voice Enabled",
languages: "Languages",
available: "Available",
heroCardTitle: "1.4 Billion People",
heroCardSubtitle: "Waiting for Financial Inclusion",
// Services
servicesTitle: "Bridging the Financial Gap",
servicesSubtitle: "Our AI-powered platform connects underserved communities with financial institutions and government programs, making banking accessible for everyone.",
microfinanceTitle: "Microfinance Connections",
microfinanceDesc: "Connect with trusted microfinance institutions tailored to your business needs.",
governmentTitle: "Government Programs",
governmentDesc: "Discover and access government subsidy programs and financial assistance.",
multilingualTitle: "Multilingual Support",
multilingualDesc: "Get assistance in your preferred language, ensuring services are truly accessible.",
voiceAiTitle: "Voice-Enabled AI",
voiceAiDesc: "Interact naturally with our AI assistant through simple voice commands.",
learnMore: "Learn More",
// Statistics
statsTitle: "Driving Global Impact",
statsSubtitle: "Our mission to democratize financial access is creating measurable change across underserved communities worldwide.",
unbankedAdults: "Unbanked Adults Worldwide",
unbankedDesc: "People without access to basic financial services",
languagesSupported: "Languages Supported",
languagesSupportedDesc: "Multilingual support for global accessibility",
successRate: "Success Rate",
successRateDesc: "Users successfully connected to financial services",
aiAssistant: "AI Assistant Available",
aiAssistantDesc: "Round-the-clock support for financial guidance",
// Features
featuresTitle: "Intelligent Financial Assistant",
featuresSubtitle: "Our AI understands your unique financial situation and connects you with the right opportunities, breaking down barriers with voice-enabled, multilingual support.",
smartMatching: "Smart Matching",
smartMatchingDesc: "AI analyzes your profile to match you with the most suitable financial products and institutions.",
voiceInteraction: "Voice Interaction",
voiceInteractionDesc: "Speak naturally in your preferred language - no need for complex forms or interfaces.",
securePrivate: "Secure & Private",
securePrivateDesc: "Your financial data is protected with enterprise-grade security and complete privacy.",
communityFocus: "Community Focus",
communityFocusDesc: "Built specifically for underserved communities with respect for local customs and needs.",



voiceAssistantActive: "Voice Assistant Active",
voiceAssistantActiveDesc: "Listening in your preferred language",
chat1: `"Help me find a small business loan"`,
chat2: "I found 3 microfinance institutions in your area. Would you like to see the options?",
chat3: `"Yes, show me the best rates"`,
// Mission
ourMission: "Our Mission",
missionText: `"To simplify finance and amplify opportunities to empower small and medium enterprises, and drive the financial inclusion for the 1.4 billion adults unbanked worldwide."`,
opportunities: "Opportunities",
opportunitiesDesc: "Endless possibilities when financial barriers are removed",
empowerment: "Empowerment",
empowermentDesc: "Building bridges between communities and financial institutions",
// CTA
ctaTitle: "Ready to Transform Your Financial Future?",
ctaSubtitle: "Join thousands of users who have already connected with financial institutions through EaseFin AI. Get started today and unlock new opportunities for your business.",
startJourney: "Start Your Journey",
scheduleDemo: "Schedule Demo",
scheduleADemo: "Schedule a Demo",
getInTouch: "Get in Touch",
getInTouchDesc: "Have questions about our platform? Our team is here to help you get started.",
contactSupport: "Contact Support",
partnerWithUs: "Partner With Us",
partnerDesc: "Are you a financial institution? Join our network and help serve underbanked communities.",
becomePartner: "Become a Partner",
verifyIdentityCTA: "Verify Identity",
verifyIdentityDesc: "Secure your account with government ID verification.",
startVerification: "Start Verification",
// Profile Setup
personalInfo: "Personal Info",
businessInfo: "Business Info",
financialInfo: "Financial Info",
preferences: "Preferences",
step: "Step",
fillOutInfo: "Please fill out the information below",
profileSetup: "Profile Setup",
// Personal Info Fields
fullName: "Full Name",
emailAddress: "Email Address",
phoneNumber: "Phone Number",
dateOfBirth: "Date of Birth",
gender: "Gender",
selectGender: "Select gender",
male: "Male",
female: "Female",
other: "Other",
preferNotToSay: "Prefer not to say",
address: "Address",
streetAddress: "Street address",
city: "City",
stateProvince: "State/Province",
postalCode: "Postal Code",
country: "Country",
selectCountry: "Select country",
selectCountryCode: "Select Country Code",
enterFullName: "Enter your full name",
// Country Names and Codes
india: "India (+91)",
bangladesh: "Bangladesh (+880)",
pakistan: "Pakistan (+92)",
sriLanka: "Sri Lanka (+94)",
oman: "Oman (+968)",
uae: "UAE (+971)",
qatar: "Qatar (+974)",
saudiArabia: "Saudi Arabia (+966)",
kuwait: "Kuwait (+965)",
bahrain: "Bahrain (+973)",
indiaCountry: "India",
bangladeshCountry: "Bangladesh",
pakistanCountry: "Pakistan",
sriLankaCountry: "Sri Lanka",
omanCountry: "Oman",
uaeCountry: "United Arab Emirates",
qatarCountry: "Qatar",
saudiArabiaCountry: "Saudi Arabia",
kuwaitCountry: "Kuwait",
bahrainCountry: "Bahrain",
// Business Info Fields
businessName: "Business Name",
businessNamePlaceholder: "Enter your business name",
businessType: "Business Type",
selectBusinessType: "Select business type",
soleProprietorship: "Sole Proprietorship",
partnership: "Partnership",
privateLimited: "Private Limited",
llp: "Limited Liability Partnership",


cooperative: "Cooperative",
businessCategory: "Business Category",
selectCategory: "Select category",
retail: "Retail",
manufacturing: "Manufacturing",
agriculture: "Agriculture",
servicesCategory: "Services",
technology: "Technology",
foodBeverage: "Food & Beverage",
textiles: "Textiles",
handicrafts: "Handicrafts",
trading: "Trading",
yearsInBusiness: "Years in Business",
selectYears: "Select years",
lessThanOneYear: "Less than 1 year",
oneToTwoYears: "1-2 years",
threeToFiveYears: "3-5 years",
sixToTenYears: "6-10 years",
moreThanTenYears: "More than 10 years",
numberOfEmployees: "Number of Employees",
selectRange: "Select range",
justMe: "Just me",
twoToFive: "2-5",
sixToTen: "6-10",
elevenToTwentyFive: "11-25",
twentySixToFifty: "26-50",
moreThanFifty: "More than 50",
averageMonthlyRevenue: "Average Monthly Revenue",
selectRevenueRange: "Select revenue range",
businessAddress: "Business Address",
businessAddressPlaceholder: "Enter your business address",
businessDescription: "Business Description",
businessDescPlaceholder: "Describe your business activities...",
// Financial Info Fields
preferredCurrency: "Preferred Currency",
selectCurrency: "Select currency",
bankAccountType: "Bank Account Type",
selectAccountType: "Select account type",
savingsAccount: "Savings Account",
currentAccount: "Current Account",
both: "Both",
noBankAccount: "No Bank Account",
monthlyIncome: "Monthly Income",
selectIncomeRange: "Select income range",
monthlyExpenses: "Monthly Expenses",
selectExpenseRange: "Select expense range",
existingLoans: "Existing Loans",
existingLoansQuestion: "Do you have existing loans?",
noExistingLoans: "No existing loans",
personalLoan: "Personal Loan",
businessLoan: "Business Loan",
homeLoan: "Home Loan",
vehicleLoan: "Vehicle Loan",
multipleLoans: "Multiple Loans",
creditScore: "Credit Score",
selectCreditScore: "Select credit score range",
dontKnow: "Don't know",
poor: "Poor (300-549)",
fair: "Fair (550-649)",
good: "Good (650-749)",
excellent: "Excellent (750-850)",
loanAmountNeeded: "Loan Amount Needed",
selectLoanAmount: "Select loan amount",
loanPurpose: "Loan Purpose",
loanPurposeQuestion: "What will you use the loan for?",
businessExpansion: "Business Expansion",
inventoryPurchase: "Inventory Purchase",
equipmentPurchase: "Equipment Purchase",
workingCapital: "Working Capital",
propertyPurchase: "Property Purchase",
education: "Education",
medicalEmergency: "Medical Emergency",
availableCollateral: "Available Collateral",
collateralPlaceholder: "Describe any collateral you can offer...",
// Preferences Fields
communicationMethod: "Communication Method",
selectMethod: "Select method",
emailComm: "Email",
smsComm: "SMS",
whatsappComm: "WhatsApp",
phoneComm: "Phone Call",
appComm: "In-App Notifications",
riskTolerance: "Risk Tolerance",
selectRisk: "Select risk level",
lowRisk: "Low - I prefer guaranteed returns",
mediumRisk: "Medium - I can accept some risk for better returns",
highRisk: "High - I'm comfortable with higher risk for potentially higher returns",
financialGoals: "Financial Goals (Select all that apply)",
buildSavings: "Build savings",
preferredLenders: "Preferred Lender Types (Select all that apply)",
lenderBanks: "Banks",
lenderMFI: "Microfinance Institutions",


lenderNBFC: "NBFCs (Non-Banking Financial Companies)",
lenderGov: "Government Schemes",
lenderCoop: "Cooperative Societies",
lenderSHG: "Self-Help Groups (SHGs)",
lenderOnline: "Online Lenders",
// Navigation
previous: "Previous",
nextStep: "Next Step",
saveProfile: "Save Profile",
// AI Agent specific translations
aiFinancialAdvisor: "AI Financial Advisor",
aiAdvisorSubtitle: "Get personalized financial recommendations",
talkToAI: "Talk to AI Assistant",
aiChatDesc: "Ask questions about loans, institutions, and financial programs",
startConversation: "Start a conversation with your AI advisor",
askAboutLoans: "Ask about loans, microfinance, or government programs",
startTalking: "Start Talking",
stopListening: "Stop Listening",
speakResponse: "Speak Response",
stopSpeaking: "Stop Speaking",
youSaid: "You said",
yourProfile: "Your Profile",
location: "Location",
business: "Business",
loanAmount: "Loan Amount",
microfinanceInstitutions: "Microfinance Institutions",
banks: "Banks",
governmentPrograms: "Government Programs",
speakingIn: "Speaking in",
aiErrorMessage: "Sorry, I'm having trouble processing your request. Please try again.",
// Financial Services
financialServicesTitle: "Financial Services Available",
financialServicesSubtitle: "Comprehensive financial solutions tailored for underserved communities",
// Service Categories
bankingAccounts: "Banking & Accounts",
creditLoans: "Credit & Loans",
investmentSavings: "Investment & Savings",
insurance: "Insurance & Protection",
supportServices: "Support & Education",
// Individual Services
lowCostAccounts: "No or Low-Cost Accounts",
lowCostAccountsDesc: "Basic bank and digital accounts with minimal fees",
mobileBanking: "Mobile & Digital Banking",
mobileBankingDesc: "Apps and mobile wallets that work across borders",
remittanceServices: "Remittance Services",
remittanceServicesDesc: "Low-cost, fast money transfers to home countries",
microloans: "Microloans & Small Business Credit",
microloansDesc: "Small capital for entrepreneurs and growing businesses",
islamicFinance: "Interest-Free Islamic Finance",
islamicFinanceDesc: "Sharia-compliant financial products and services",
savingsGroups: "Savings Groups & Community Circles",
savingsGroupsDesc: "Peer-based saving and lending within communities",
creditBuilding: "Credit Building & Alternative Scoring",
creditBuildingDesc: "Building credit using utility, rent, and phone payment data",
financialEducation: "Financial Education & Literacy",
financialEducationDesc: "Financial training in native languages, culturally sensitive",
financialCoaching: "Financial Coaching & Mentoring",
financialCoachingDesc: "Ongoing support tailored to migrant and underbanked life",
diasporaInvestment: "Diaspora Investment Channels",
diasporaInvestmentDesc: "Safe ways to invest back in home countries",
microInsurance: "Micro-Insurance & Health Cover",
microInsuranceDesc: "Low-cost life, health, and risk protection",
legalHelp: "Legal & Regulatory Help",
legalHelpDesc: "Navigate foreign laws and understand banking rights",
digitalIdentity: "Digital Identity & Simplified KYC",
digitalIdentityDesc: "Using passports, remittance histories, and alternative documents",
crossBorderBanking: "Cross-Border Banking Partnerships",
crossBorderBankingDesc: "Accounts and services linking host and home countries",
communityBanks: "Community Credit Unions & Diaspora Banks",
communityBanksDesc: "Financial institutions run by and for migrant communities",
// Service Features
lowFees: "Low Fees",
crossBorder: "Cross-Border",
shariaCompliant: "Sharia Compliant",


communityBased: "Community Based",
multilingual: "Multilingual Support",
noCredit: "No Credit History Required",
instant: "Instant Approval",
secure: "Bank-Level Security",
// Contact Page
sendMessage: "Send a Message",
subject: "Subject",
message: "Message",
emailUs: "Email Us",
emailDesc: "Contact our support team directly at support@easefin.ai",
submitInquiry: "Submit Inquiry",
// Partner Page
whyPartnerWithUs: "Why Partner with EaseFin AI?",
expandYourReach: "Expand Your Reach",
expandReachDesc: "Connect with a vast, untapped market of unbanked and underbanked individuals.",
overcomeBarriers: "Overcome Barriers",
overcomeBarriersDesc: "Our multilingual, voice-enabled AI breaks down language and literacy hurdles.",
driveSocialImpact: "Drive Social Impact",
socialImpactDesc: "Be a part of a global movement to foster financial inclusion and empower communities.",
partnershipInquiry: "Partnership Inquiry",
partnershipInquiryDesc: "Fill out the form below to start the conversation about joining our network.",
institutionName: "Institution Name",
contactPerson: "Contact Person",
messageOptional: "Message (Optional)",
// Gov ID Verification Page
govIdVerification: "Government ID Verification",
verifyIdentitySubtitle: "Secure your account and unlock full access to financial services.",
uploadId: "Upload Your Government ID",
uploadIdDesc: "Please select the type of ID and upload a clear image of the front and back.",
selectIdType: "Select ID Type",
chooseIdType: "Choose an ID type",
passports: "Passport",
nationalIdCards: "National ID Card",
drivingLicenses: "Driving License",
voterIdCards: "Voter ID Card",
aadharCard: "Aadhar Card (India)",
pakistanIdCard: "CNIC (Pakistan)",
bangladeshIdCard: "NID (Bangladesh)",
emiratesId: "Emirates ID (UAE)",
iqamaSaudi: "Iqama (Saudi Arabia)",
omaniResidentCard: "Resident Card (Oman)",
qatarId: "QID (Qatar)",
kuwaitCivilId: "Civil ID (Kuwait)",
bahrainCpr: "CPR Card (Bahrain)",
uploadFrontSide: "Upload Front Side",
uploadBackSide: "Upload Back Side",
clickToSelectFile: "Click to select a file",
frontUploadedSuccess: "Front side uploaded!",
backUploadedSuccess: "Back side uploaded!",
verifyIdentity: "Verify My Identity",
compFinancialServices: "Comprehensive Financial Services",
financialServices: "Financial Services",
microfinance: "Microfinance",
currencyExchange: "Currency Exchange",
creditUnionServices: "Credit Union Services",
additionalServices: "Additional Services",
paymentServices: "Payment Services",
insuranceServices: "Insurance Services",
emergencyCredit: "Emergency Credit",
billPayments: "Bill Payments",
idVerifiedSuccess: "Identity Verified Successfully!",
idVerifiedSuccessDesc: "You can now proceed to the next step or explore financial services.",
continueToFaceVerification: "Continue to Face Verification",
backToHome: "Back to Home",
verifyIdentityFirst: "Verify Identity First",
consultAI: "Consult AI",
},
"हि ंदी (Hindi)": {
// Header & Navigation
selectLanguage: "भाषा चुनें",
createProfile: "प्रोफ़ाइल बनाएं ",
aiAgent: "एआई एजेंट",
financialServicesNav: "वि त्तीय सेवाएं ",
partnersNav: "भागीदार",
// Hero Section
aiPowered: "AI-संचालि त वि त्तीय समावेश",
heroTitle: "बि ना बैंक खाते वालों का सशक्ति करण",
heroSubtitle: "हमारे बहुभाषी AI सहायक के माध्यम से माइक्रोफाइनेंस संस्थानों, छोटे बैंकों और सरकारी कार्यक्रमों से जुड़ें। दुनि या भर के 1.4 अरब वयस्कों के लि ए वि त्तीय सेवाओं को सुलभ बनाना।",
getStarted: "आज ही शुरुआत करें",
watchDemo: "डेमो देखें",
voiceEnabled: "आवाज सक्षम",
languages: "भाषाएं ",
available: "उपलब्ध",
heroCardTitle: "1.4 अरब लोग",
heroCardSubtitle: "वि त्तीय समावेश की प्रतीक्षा में",


// Services
servicesTitle: "वि त्तीय अंतर को पाटना",
servicesSubtitle: "हमारा AI-संचालि त प्लेटफॉर्म वंचि त समुदायों को वि त्तीय संस्थानों और सरकारी कार्यक्रमों से जोड़ता है, सभी के लि ए बैंकि ंग को सुलभ बनाता है।",
microfinanceTitle: "माइक्रोफाइनेंस कनेक्शन",
microfinanceDesc: "अपनी व्यावसायि क आवश्यकताओं के अनुरूप वि श्वसनीय माइक्रोफाइनेंस संस्थानों से जुड़ें।",
governmentTitle: "सरकारी कार्यक्रम",
governmentDesc: "सरकारी सब्सि डी कार्यक्रमों और वि त्तीय सहायता की खोज और पहुंच प्राप्त करें।",
multilingualTitle: "बहुभाषी समर्थन",
multilingualDesc: "अपनी पसंदीदा भाषा में सहायता प्राप्त करें, यह सुनि श्चि त करते हुए कि सेवाएं वास्तव में सुलभ हों।",
voiceAiTitle: "आवाज-सक्षम AI",
voiceAiDesc: "सरल आवाज कमांड के माध्यम से हमारे AI सहायक के साथ प्राकृति क रूप से बातचीत करें।",
learnMore: "और जानें",
// Statistics
statsTitle: "वैश्वि क प्रभाव चलाना",
statsSubtitle: "वि त्तीय पहुंच को लोकतांत्रि क बनाने का हमारा मि शन दुनि या भर के वंचि त समुदायों में मापने योग्य परि वर्तन ला रहा है।",
unbankedAdults: "दुनि या भर में बि ना बैंक खाते वाले वयस्क",
unbankedDesc: "बुनि यादी वि त्तीय सेवाओं तक पहुंच न रखने वाले लोग",
languagesSupported: "समर्थि त भाषाएं ",
languagesSupportedDesc: "वैश्वि क पहुंच के लि ए बहुभाषी समर्थन",
successRate: "सफलता दर",
successRateDesc: "वि त्तीय सेवाओं से सफलतापूर्वक जुड़े उपयोगकर्ता ",
aiAssistant: "AI सहायक उपलब्ध",
aiAssistantDesc: "वि त्तीय मार्गदर्शन के लि ए चौबीसों घंटे सहायता",
// Features
featuresTitle: "बुद्धि मान वि त्तीय सहायक",
featuresSubtitle: "हमारा AI आपकी अनूठी वि त्तीय स्थि ति को समझता है और आपको सही अवसरों से जोड़ता है, आवाज-सक्षम, बहुभाषी समर्थन के साथ बाधाओं को तोड़ता है।",
smartMatching: "स्मार्ट मैचि ंग",
smartMatchingDesc: "AI आपकी प्रोफाइल का वि श्लेषण करता है और आपको सबसे उपयुक्त वि त्तीय उत्पादों और संस्थानों से मि लाता है।",
voiceInteraction: "आवाज इंटरैक्शन",
voiceInteractionDesc: "अपनी पसंदीदा भाषा में स्वाभावि क रूप से बोलें - जटि ल फॉर्म या इंटरफेस की आवश्यकता नहीं।",
securePrivate: "सुरक्षि त और नि जी",
securePrivateDesc: "आपका वि त्तीय डेटा एं टरप्राइज़-ग्रेड सुरक्षा और पूर्ण गोपनीयता के साथ सुरक्षि त है।",
communityFocus: "सामुदायि क फोकस",
communityFocusDesc: "स्थानीय रीति -रि वाजों और जरूरतों का सम्मान करते हुए वि शेष रूप से वंचि त समुदायों के लि ए नि र्मि त।",
voiceAssistantActive: "वॉयस असि स्टेंट सक्रि य",
voiceAssistantActiveDesc: "आपकी पसंदीदा भाषा में सुन रहा है",
chat1: `"मुझे छोटे व्यापार ऋण खोजने में मदद करें"`,
chat2: "मुझे आपके क्षेत्र में 3 माइक्रोफाइनेंस संस्थान मि ली हैं। क्या आप वि कल्प देखना चाहते हैं?",
chat3: `"हाँ, मुझे सबसे अच्छी दरें दि खाएं "`,
// Mission
ourMission: "हमारा मि शन",
missionText: `"वि त्त को सरल बनाना और छोटे और मध्यम उद्यमों को सशक्त बनाने के अवसरों को बढ़ावा देना, और दुनि या भर में 1.4 अरब वयस्कों के लि ए वि त्तीय समावेश को बढ़ावादेना।"`,
opportunities: "अवसर",
opportunitiesDesc: "जब वि त्तीय बाधाएं हटा दी जाती हैं तो अनंत संभावनाएं ",
empowerment: "सशक्ति करण",
empowermentDesc: "समुदायों और वि त्तीय संस्थानों के बीच पुल नि र्मा ण",
// CTA
ctaTitle: "अपना वि त्तीय भवि ष्य बदलने के लि ए तैयार हैं?",
ctaSubtitle: "हजारों उपयोगकर्ता ओं के साथ जुड़ें जो पहले से ही EaseFin AI के माध्यम से वि त्तीय संस्थानों से जुड़े हुए हैं। आज ही शुरुआत करें और अपने व्यापार के लि ए नए अवसर अनलॉक करें।",
startJourney: "अपनी यात्रा शुरू करें",
scheduleDemo: "डेमो शेड्यूल करें",
scheduleADemo: "एक डेमो शेड्यूल करें",
getInTouch: "संपर्क करें",
getInTouchDesc: "हमारे प्लेटफॉर्म के बारे में प्रश्न हैं? हमारी टीम आपको शुरुआत करने में मदद करने के लि ए यहाँ है।",
contactSupport: "सहायता से संपर्क करें",
partnerWithUs: "हमारे साथ साझेदारी करें",
partnerDesc: "क्या आप एक वि त्तीय संस्था हैं? हमारे नेटवर्क में शामि ल हों और वंचि त समुदायों की सेवा में मदद करें।",
becomePartner: "साझेदार बनें",
verifyIdentityCTA: "पहचान सत्यापि त करें",
verifyIdentityDesc: "सरकारी आईडी सत्यापन के साथ अपना खाता सुरक्षि त करें।",
startVerification: "सत्यापन शुरू करें",
// Profile Setup
personalInfo: "व्यक्ति गत जानकारी",
businessInfo: "व्यवसाय जानकारी",
financialInfo: "वि त्तीय जानकारी",
preferences: "प्राथमि कताएं ",
step: "चरण",
fillOutInfo: "कृपया नीचे दी गई जानकारी भरें",
profileSetup: "प्रोफ़ाइल सेटअप",
// Personal Info Fields - Hindi
fullName: "पूरा नाम",
emailAddress: "ईमेल पता",
phoneNumber: "फ़ोन नंबर",
dateOfBirth: "जन्म की तारीख",
gender: "लि ंग",
selectGender: "लि ंग चुनें",
male: "पुरुष",
female: "महि ला",
other: "अन्य",
preferNotToSay: "बताना नहीं चाहते",
address: "पता",
streetAddress: "गली का पता",
city: "शहर",
stateProvince: "राज्य/प्रांत",
postalCode: "डाक कोड",


country: "देश",
selectCountry: "देश चुनें",
selectCountryCode: "देश कोड चुनें",
enterFullName: "अपना पूरा नाम दर्ज करें",
// Business Info Fields - Hindi
businessName: "व्यवसाय का नाम",
businessNamePlaceholder: "अपने व्यवसाय का नाम दर्ज करें",
businessType: "व्यवसाय का प्रकार",
selectBusinessType: "व्यवसाय का प्रकार चुनें",
soleProprietorship: "एकल स्वामि त्व",
partnership: "साझेदारी",
privateLimited: "प्राइवेट लि मि टेड",
llp: "सीमि त देयता भागीदारी",
cooperative: "सहकारी",
businessCategory: "व्यवसाय श्रेणी",
selectCategory: "श्रेणी चुनें",
retail: "खुदरा",
manufacturing: "वि नि र्मा ण",
agriculture: "कृषि ",
servicesCategory: "सेवाएं ",
technology: "प्रौद्योगि की",
foodBeverage: "खाद्य और पेय",
textiles: "कपड़ा",
handicrafts: "हस्तशि ल्प",
trading: "व्यापार",
yearsInBusiness: "व्यवसाय में वर्ष",
selectYears: "वर्ष चुनें",
lessThanOneYear: "1 वर्ष से कम",
oneToTwoYears: "1-2 वर्ष",
threeToFiveYears: "3-5 वर्ष",
sixToTenYears: "6-10 वर्ष",
moreThanTenYears: "10 से अधि क वर्ष",
numberOfEmployees: "कर्मचारि यों की संख्या",
selectRange: "रेंज चुनें",
justMe: "केवल मैं",
twoToFive: "2-5",
sixToTen: "6-10",
elevenToTwentyFive: "11-25",
twentySixToFifty: "26-50",
moreThanFifty: "50 से अधि क",
averageMonthlyRevenue: "औसत मासि क राजस्व",
selectRevenueRange: "राजस्व सीमा चुनें",
businessAddress: "व्यवसाय का पता",
businessAddressPlaceholder: "अपने व्यवसाय का पता दर्ज करें",
businessDescription: "व्यवसाय का वि वरण",
businessDescPlaceholder: "अपनी व्यावसायि क गति वि धि यों का वर्णन करें...",
// Financial Info Fields - Hindi
preferredCurrency: "पसंदीदा मुद्रा",
selectCurrency: "मुद्रा चुनें",
bankAccountType: "बैंक खाता प्रकार",
selectAccountType: "खाता प्रकार चुनें",
savingsAccount: "बचत खाता",
currentAccount: "चालू खाता",
both: "दोनों",
noBankAccount: "कोई बैंक खाता नहीं",
monthlyIncome: "मासि क आय",
selectIncomeRange: "आय सीमा चुनें",
monthlyExpenses: "मासि क व्यय",
selectExpenseRange: "व्यय सीमा चुनें",
existingLoans: "मौजूदा ऋण",
existingLoansQuestion: "क्या आपके पास मौजूदा ऋण हैं?",
noExistingLoans: "कोई मौजूदा ऋण नहीं",
personalLoan: "व्यक्ति गत ऋण",
businessLoan: "व्यापार ऋण",
homeLoan: "गृह ऋण",
vehicleLoan: "वाहन ऋण",
multipleLoans: "कई ऋण",
creditScore: "क्रेडि ट स्कोर",
selectCreditScore: "क्रेडि ट स्कोर सीमा चुनें",
dontKnow: "पता नहीं",
poor: "खराब (300-549)",
fair: "ठीक (550-649)",
good: "अच्छा (650-749)",
excellent: "उत्कृष्ट (750-850)",
loanAmountNeeded: "आवश्यक ऋण राशि ",
selectLoanAmount: "ऋण राशि चुनें",
loanPurpose: "ऋण का उद्देश्य",
loanPurposeQuestion: "आप ऋण का उपयोग कि स लि ए करेंगे?",
businessExpansion: "व्यापार वि स्तार",
inventoryPurchase: "इन्वेंट्री खरीद",
equipmentPurchase: "उपकरण खरीद",
workingCapital: "कार्यशील पूंजी",
propertyPurchase: "संपत्ति खरीद",
education: "शि क्षा",
medicalEmergency: "चि कि त्सा आपातकाल",
availableCollateral: "उपलब्ध संपार्श्वि क",
collateralPlaceholder: "आप जो भी संपार्श्वि क दे सकते हैं उसका वर्णन करें...",
// Preferences Fields - Hindi
communicationMethod: "संचार वि धि ",
selectMethod: "वि धि चुनें",
emailComm: "ईमेल",


smsComm: "एसएमएस",
whatsappComm: "व्हाट् सएप",
phoneComm: "फोन कॉल",
appComm: "इन-ऐप सूचनाएं ",
riskTolerance: "जोखि म सहनशीलता",
selectRisk: "जोखि म स्तर चुनें",
lowRisk: "कम - मैं गारंटीकृत रि टर्न पसंद करता हूं",
mediumRisk: "मध्यम - मैं बेहतर रि टर्न के लि ए कुछ जोखि म स्वीकार कर सकता हूं",
highRisk: "उच्च - मैं संभावि त रूप से उच्च रि टर्न के लि ए उच्च जोखि म के साथ सहज हूं",
financialGoals: "वि त्तीय लक्ष्य (सभी लागू चुनें)",
buildSavings: "बचत का नि र्मा ण करें",
preferredLenders: "पसंदीदा ऋणदाता प्रकार (सभी लागू चुनें)",
lenderBanks: "बैंक",
lenderMFI: "माइक्रोफाइनेंस संस्थान",
lenderNBFC: "एनबीएफसी (गैर-बैंकि ंग वि त्तीय कंपनि यां)",
lenderGov: "सरकारी योजनाएं ",
lenderCoop: "सहकारी समि ति यां",
lenderSHG: "स्वयं सहायता समूह (एसएचजी)",
lenderOnline: "ऑनलाइन ऋणदाता",
// Navigation
previous: "पि छला",
nextStep: "अगला चरण",
saveProfile: "प्रोफ़ाइल सहेजें",
// AI Agent specific translations
aiFinancialAdvisor: "एआई वि त्तीय सलाहकार",
aiAdvisorSubtitle: "व्यक्ति गत वि त्तीय सि फारि शें प्राप्त करें",
talkToAI: "एआई सहायक से बात करें",
aiChatDesc: "ऋण, संस्थानों और वि त्तीय कार्यक्रमों के बारे में प्रश्न पूछें",
startConversation: "अपने एआई सलाहकार के साथ बातचीत शुरू करें",
askAboutLoans: "ऋण, माइक्रोफाइनेंस या सरकारी कार्यक्रमों के बारे में पूछें",
startTalking: "बोलना शुरू करें",
stopListening: "सुनना बंद करें",
speakResponse: "जवाब बोलें",
stopSpeaking: "बोलना बंद करें",
youSaid: "आपने कहा",
yourProfile: "आपकी प्रोफ़ाइल",
location: "स्थान",
business: "व्यवसाय",
loanAmount: "ऋण राशि ",
microfinanceInstitutions: "माइक्रोफाइनेंस संस्थान",
banks: "बैंक",
governmentPrograms: "सरकारी कार्यक्रम",
speakingIn: "में बोल रहा हूं",
aiErrorMessage: "क्षमा करें, मुझे आपके अनुरोध को संसाधि त करने में समस्या हो रही है। कृपया पुनः प्रयास करें।",
// Financial Services
financialServicesTitle: "उपलब्ध वि त्तीय सेवाएं ",
financialServicesSubtitle: "वंचि त समुदायों के लि ए व्यापक वि त्तीय समाधान",
// Service Categories
bankingAccounts: "बैंकि ंग और खाते",
creditLoans: "क्रेडि ट और ऋण",
investmentSavings: "नि वेश और बचत",
insurance: "बीमा और सुरक्षा",
// Individual Services
lowCostAccounts: "कम या बि ना फीस वाले खाते",
lowCostAccountsDesc: "न्यूनतम फीस के साथ बुनि यादी बैंक और डि जि टल खाते",
mobileBanking: "मोबाइल और डि जि टल बैंकि ंग",
mobileBankingDesc: "सीमा पार काम करने वाले ऐप्स और मोबाइल वॉलेट",
remittanceServices: "रेमि टेंस सेवाएं ",
remittanceServicesDesc: "घर देश में कम लागत, तेज़ पैसा भेजना",
microloans: "माइक्रोलोन और छोटे व्यापार क्रेडि ट",
microloansDesc: "उद्यमि यों और बढ़ते व्यापार के लि ए छोटी पूंजी",
islamicFinance: "ब्याज-मुक्त इस्लामी वि त्त",
islamicFinanceDesc: "शरि या-अनुपालि त वि त्तीय उत्पाद और सेवाएं ",
savingsGroups: "बचत समूह और सामुदायि क चक्र",
savingsGroupsDesc: "समुदायों के भीतर साथि यों पर आधारि त बचत और उधार",
creditBuilding: "क्रेडि ट नि र्मा ण और वैकल्पि क स्कोरि ंग",
creditBuildingDesc: "उपयोगि ता, कि राया और फोन भुगतान डेटा का उपयोग करके क्रेडि ट बनाना",
financialEducation: "वि त्तीय शि क्षा और साक्षरता",
financialEducationDesc: "मूल भाषाओं में वि त्तीय प्रशि क्षण, सांस्कृति क रूप से संवेदनशील",
financialCoaching: "वि त्तीय कोचि ंग और मार्गदर्शन",
financialCoachingDesc: "प्रवासी और अनबैंक्ड जीवन के लि ए नि रंतर सहायता",
diasporaInvestment: "प्रवासी नि वेश चैनल",
diasporaInvestmentDesc: "मूल देशों में नि वेश करने के सुरक्षि त तरीके",
microInsurance: "सूक्ष्म बीमा और स्वास्थ्य कवर",
microInsuranceDesc: "कम लागत वाला जीवन, स्वास्थ्य और जोखि म सुरक्षा",
legalHelp: "कानूनी और नि यामक सहायता",
legalHelpDesc: "वि देशी कानूनों का नेवीगेट करना और बैंकि ंग अधि कारों को समझना",


digitalIdentity: "डि जि टल पहचान और सरलीकृत KYC",
digitalIdentityDesc: "पासपोर्ट, रेमि टेंस इति हास और वैकल्पि क दस्तावेजों का उपयोग",
crossBorderBanking: "सीमा-पार बैंकि ंग भागीदारी",
crossBorderBankingDesc: "मेजबान और मूल देशों को जोड़ने वाले खाते और सेवाएं ",
communityBanks: "सामुदायि क क्रेडि ट यूनि यन और प्रवासी बैंक",
communityBanksDesc: "प्रवासी समुदायों द्वारा और उनके लि ए संचालि त वि त्तीय संस्थान",
supportServices: "सहायता और शि क्षा",
// Service Features
lowFees: "कम फीस",
crossBorder: "सीमा-पार",
shariaCompliant: "शरि या अनुपालि त",
communityBased: "समुदाय आधारि त",
multilingual: "बहुभाषी समर्थन",
noCredit: "क्रेडि ट इति हास की आवश्यकता नहीं",
instant: "तत्काल अनुमोदन",
secure: "बैंक-स्तरीय सुरक्षा",
// Contact Page
sendMessage: "संदेश भेजें",
subject: "वि षय",
message: "संदेश",
emailUs: "हमें ईमेल करें",
emailDesc: "हमारी सहायता टीम से सीधे support@easefin.ai पर संपर्क करें",
submitInquiry: "पूछताछ भेजें",
// Partner Page
whyPartnerWithUs: "EaseFin AI के साथ साझेदारी क्यों करें?",
expandYourReach: "अपनी पहुंच बढ़ाएं ",
expandReachDesc: "बैंक रहि त और अल्प-बैंक वाले व्यक्ति यों के एक वि शाल, अछू ते बाजार से जुड़ें।",
overcomeBarriers: "बाधाओं को दूर करें",
overcomeBarriersDesc: "हमारा बहुभाषी, आवाज-सक्षम AI भाषा और साक्षरता की बाधाओं को तोड़ता है।",
driveSocialImpact: "सामाजि क प्रभाव डालें",
socialImpactDesc: "वि त्तीय समावेशन को बढ़ावा देने और समुदायों को सशक्त बनाने के वैश्वि क आंदोलन का हि स्सा बनें।",
partnershipInquiry: "साझेदारी पूछताछ",
partnershipInquiryDesc: "हमारे नेटवर्क में शामि ल होने के बारे में बातचीत शुरू करने के लि ए नीचे दि या गया फॉर्म भरें।",
institutionName: "संस्था का नाम",
contactPerson: "संपर्क व्यक्ति ",
messageOptional: "संदेश (वैकल्पि क)",
// Gov ID Verification Page
govIdVerification: "सरकारी आईडी सत्यापन",
verifyIdentitySubtitle: "अपना खाता सुरक्षि त करें और वि त्तीय सेवाओं तक पूरी पहुंच अनलॉक करें।",
uploadId: "अपनी सरकारी आईडी अपलोड करें",
uploadIdDesc: "कृपया आईडी का प्रकार चुनें और आगे और पीछे की एक स्पष्ट छवि अपलोड करें।",
selectIdType: "आईडी प्रकार चुनें",
chooseIdType: "एक आईडी प्रकार चुनें",
passports: "पासपोर्ट",
nationalIdCards: "राष्ट्र ीय पहचान पत्र",
drivingLicenses: "ड्र ाइवि ंग लाइसेंस",
voterIdCards: "मतदाता पहचान पत्र",
aadharCard: "आधार कार्ड (भारत)",
pakistanIdCard: "CNIC (पाकि स्तान)",
bangladeshIdCard: "NID (बांग्लादेश)",
emiratesId: "एमि रेट्स आईडी (यूएई)",
iqamaSaudi: "इकामा (सऊदी अरब)",
omaniResidentCard: "रेजि डेंट कार्ड (ओमान)",
qatarId: "QID (कतर)",
kuwaitCivilId: "सि वि ल आईडी (कुवैत)",
bahrainCpr: "CPR कार्ड (बहरीन)",
uploadFrontSide: "सामने का हि स्सा अपलोड करें",
uploadBackSide: "पि छला हि स्सा अपलोड करें",
clickToSelectFile: "फ़ाइल चुनने के लि ए क्लि क करें",
frontUploadedSuccess: "सामने का हि स्सा अपलोड हो गया!",
backUploadedSuccess: "पि छला हि स्सा अपलोड हो गया!",
verifyIdentity: "मेरी पहचान सत्यापि त करें",
compFinancialServices: "व्यापक वि त्तीय सेवाएं ",
financialServices: "वि त्तीय सेवाएं ",
microfinance: "माइक्रोफाइनेंस",
currencyExchange: "मुद्रा वि नि मय",
creditUnionServices: "क्रेडि ट यूनि यन सेवाएं ",
additionalServices: "अति रि क्त सेवाएं ",
paymentServices: "भुगतान सेवाएं ",
insuranceServices: "बीमा सेवाएं ",
emergencyCredit: "आपातकालीन क्रेडि ट",
billPayments: "बि ल भुगतान",
idVerifiedSuccess: "पहचान सफलतापूर्वक सत्यापि त!",
idVerifiedSuccessDesc: "अब आप अगले चरण पर जा सकते हैं या वि त्तीय सेवाओं का पता लगा सकते हैं।",
continueToFaceVerification: "चेहरा सत्यापन के लि ए आगे बढ़ें ",
backToHome: "होम पर वापस जाएं ",
verifyIdentityFirst: "पहले पहचान सत्यापि त करें",
consultAI: "AI से सलाह लें",
},
"‫اردو (Urdu)": {},
"‫العربية (Arabic)": {},
"தமிழ் (Tamil)": {},
"తెలుగు (Telugu)": {},
"ਪੰਜਾਬੀ (Punjabi)": {},
"বাংলা (Bengali)": {},
};

const LanguageContext = createContext();
export const useLanguage = () => {
const context = useContext(LanguageContext);
if (!context) {
throw new Error('useLanguage must be used within a LanguageProvider');
}
return context;
};
export const LanguageProvider = ({ children }) => {
const [currentLanguage, setCurrentLanguage] = useState('English');
const t = (key) => {
return translations[currentLanguage]?.[key] || translations['English'][key] || key;
};
// Check if current language is RTL
const isRTL = useCallback(() => {
const rtlLanguages = ['‫( اردو‬Urdu)', '‫( العربية‬Arabic)'];
return rtlLanguages.includes(currentLanguage);
}, [currentLanguage]); // currentLanguage is a dependency for useCallback
// Get text alignment class based on language direction
const getTextAlign = (defaultAlign = 'left') => {
if (isRTL()) {
return defaultAlign === 'left' ? 'text-right' : defaultAlign === 'right' ? 'text-left' : `text-${defaultAlign}`;
}
return `text-${defaultAlign}`;
};
// Get flex direction for RTL
const getFlexDirection = () => {
return isRTL() ? 'flex-row-reverse' : 'flex-row';
};
useEffect(() => {
// Set dir attribute on the root html element
document.documentElement.dir = isRTL() ? 'rtl' : 'ltr';
// Set lang attribute on the root html element
document.documentElement.lang = currentLanguage.split(' ')[0].toLowerCase();
}, [currentLanguage, isRTL]); // Added isRTL to dependencies after memoization
const value = {
currentLanguage,
setCurrentLanguage,
t,
isRTL: isRTL(), // Expose the boolean result of the function
getTextAlign,
getFlexDirection
};
return (
<LanguageContext.Provider value={value}>
{/* Apply dir attribute and class to a wrapper div for component-specific styling and layout adjustments */}
<div className={isRTL() ? 'rtl' : 'ltr'} dir={isRTL() ? 'rtl' : 'ltr'}>
{children}
</div>
</LanguageContext.Provider>
);
};
export default LanguageContext;
